version: 2
sources:
  - name: datafeed_shared_schema
    database: "{{('myown_db')}}"
    schema: dev_dbt
    tables:
      - name: raw_customer
      - name: cust
      - name : raw_orders
        columns:
            - name: order_key
              tests:
                - unique
                - not_null
            - name: ORDER_STATUS
              tests:
                - accepted_values:
                      values: ['F', 'P']
      - name : CUSTOMERS

